# 云服务器配置文件示例
# 复制此文件并修改为你的实际配置

# 阿里云ECS配置示例
aliyun:
  host: "123.456.789.100"  # 你的服务器公网IP
  user: "root"             # SSH用户名
  port: 22                 # SSH端口
  gpu: true                # 是否有GPU
  instance_type: "ecs.gn6i-c4g1.xlarge"  # 实例类型
  region: "cn-beijing"     # 地域

# 腾讯云CVM配置示例  
tencent:
  host: "123.456.789.101"
  user: "ubuntu"
  port: 22
  gpu: true
  instance_type: "GN7.LARGE20"
  region: "ap-beijing"

# 华为云ECS配置示例
huawei:
  host: "123.456.789.102"
  user: "root"  
  port: 22
  gpu: true
  instance_type: "ai1.2xlarge.8"
  region: "cn-north-4"

# 自建服务器配置示例
custom:
  host: "your-server.com"
  user: "ubuntu"
  port: 22
  gpu: true
  
# 推荐配置要求
requirements:
  cpu: "8+ 核心"
  memory: "32+ GB"
  storage: "100+ GB SSD"
  gpu: "Tesla T4 / V100 / A100"
  bandwidth: "10+ Mbps"
  
# 成本估算（每月，仅供参考）
cost_estimate:
  aliyun_gpu: "800-2000 RMB"
  tencent_gpu: "700-1800 RMB" 
  huawei_gpu: "750-1900 RMB"
  aws_gpu: "150-400 USD"
  gcp_gpu: "140-380 USD"