# LightGBM 优化训练配置文件
# 针对大规模时序股票数据的深度优化版本
#
# 优化要点：
# 1. 改进异常值处理：使用更严格的阈值和多重过滤
# 2. 增强特征工程：更丰富的统计特征和技术指标
# 3. 优化超参数搜索：针对大数据集的参数范围调整
# 4. 实施分层训练：处理数据不平衡问题
# 5. 加强正则化：防止过拟合

# ===========================================
# 数据配置
# ===========================================
data:
  # 数据路径配置
  data_dir: "./data/datas_processed/processed_20250810_015407"
  
  # 数据文件名称 (CSV格式)
  X_features_file: "X_features.csv"
  y_targets_file: "y_targets.csv"
  full_data_file: "full_data.csv"
  stock_codes_file: "stock_codes.json"
  data_info_file: "data_info.json"
  
  # 数据加载选项
  loading_options:
    prefer_full_data: true
    encoding: "utf-8"
    validate_data: true
    
  # 时序窗口数据选项
  timeseries_window:
    validate_completeness: true
    min_samples_per_stock: 10  # 提高最小样本要求
    show_window_analysis: true
  
  # 数据预处理 - 重大优化
  preprocessing:
    # 改用flatten方法保留更多时序信息
    timeseries_method: "flatten"
    
    # 增强特征工程
    feature_engineering:
      # 更丰富的统计特征
      statistical_features:
        - "mean"        # 均值
        - "std"         # 标准差
        - "max"         # 最大值
        - "min"         # 最小值
        - "median"      # 中位数
        - "skew"        # 偏度
        - "kurtosis"    # 峰度
        - "quantile_25" # 25%分位数
        - "quantile_75" # 75%分位数
        - "range"       # 极差
        - "cv"          # 变异系数
        
      # 增强技术指标特征
      technical_features:
        enabled: true
        features:
          - "momentum"       # 动量特征
          - "volatility"     # 波动率特征
          - "trend"          # 趋势特征
          - "rsi"            # 相对强弱指标
          - "moving_average" # 移动平均
          - "bollinger"      # 布林带
          - "macd"           # MACD指标
    
    # 增强数据标准化
    normalization:
      method: "robust"  # 改用robust标准化，对异常值更鲁棒
      
    # 严格异常值处理 - 关键优化
    outlier_handling:
      enabled: true
      method: "multi_stage"  # 多阶段异常值处理
      # 第一阶段：极端异常值处理
      extreme_threshold: 5.0  # 超过5个标准差的视为极端异常值
      # 第二阶段：温和异常值处理
      mild_threshold: 2.5     # 超过2.5个标准差的进行调整
      # 处理策略
      strategy: "winsorize"   # "remove", "winsorize", "clip"
      winsorize_limits: [0.01, 0.01]  # 1%和99%分位数截断

# ===========================================
# 训练配置 - 优化版
# ===========================================
training:
  # 数据分割 - 针对时序数据优化
  data_split:
    test_size: 0.15      # 减少测试集，增加训练数据
    validation_size: 0.15 # 增加验证集用于早停
    random_state: 42
    stratify: false
    # 时序分割选项
    time_series_split: true  # 使用时序分割而非随机分割
    
  # 交叉验证 - 优化
  cross_validation:
    enabled: true
    cv_folds: 3          # 减少折数，提高训练效率
    cv_strategy: "time_series"
    
  # 训练参数 - 优化
  training_params:
    early_stopping_rounds: 50  # 减少早停轮数，防止过早停止
    verbose: 50
    eval_metric: ["rmse", "mae", "mape"]

# ===========================================
# LightGBM 模型参数 - 大幅优化
# ===========================================
lightgbm:
  # 基础参数 - 针对大数据集优化
  basic_params:
    objective: "regression"
    metric: "rmse"
    boosting_type: "gbdt"
    num_leaves: 127        # 增加叶子数，提升模型复杂度
    learning_rate: 0.05    # 降低学习率，提高稳定性
    feature_fraction: 0.8  # 降低特征采样，减少过拟合
    bagging_fraction: 0.7  # 降低样本采样，增强泛化
    bagging_freq: 3        # 增加bagging频率
    verbose: -1
    random_state: 42
    
  # 进阶参数 - 强化正则化
  advanced_params:
    max_depth: 8           # 限制树深度，防止过拟合
    min_data_in_leaf: 100  # 增加叶子最小样本数
    min_gain_to_split: 0.1 # 增加分裂增益阈值
    lambda_l1: 1.0         # 增加L1正则化
    lambda_l2: 1.0         # 增加L2正则化
    min_data_in_bin: 5     # 提高分箱最小样本数
    bin_construct_sample_cnt: 500000  # 增加分箱采样数
    max_bin: 255           # 增加最大分箱数
    
  # 训练参数
  fit_params:
    num_boost_round: 2000  # 增加训练轮数
    categorical_feature: "auto"

# ===========================================
# 特征选择 - 强化版
# ===========================================
feature_selection:
  enabled: true
  methods:
    # 基于重要性的选择 - 更严格
    importance_based:
      enabled: true
      threshold: 0.01    # 提高重要性阈值10倍
      method: "gain"     # 使用gain而非split
      
    # 基于相关性的选择 - 更严格
    correlation_based:
      enabled: true
      threshold: 0.90    # 降低相关性阈值
      
    # 启用递归特征消除
    rfe:
      enabled: true
      n_features_to_select: 200  # 选择最重要的200个特征
      step: 0.1          # 每次消除10%的特征

# ===========================================
# 超参数优化 - 深度优化
# ===========================================
hyperparameter_tuning:
  enabled: true
  method: "optuna"
  
  # Optuna 配置 - 更全面的搜索
  optuna_config:
    n_trials: 50       # 增加试验次数
    timeout: 3600      # 1小时超时
    
    # 参数搜索空间 - 针对大数据集优化
    param_ranges:
      num_leaves: [63, 255]           # 更大的叶子数范围
      learning_rate: [0.01, 0.15]     # 更保守的学习率
      feature_fraction: [0.6, 0.9]    # 适中的特征采样
      bagging_fraction: [0.6, 0.9]    # 适中的样本采样
      min_data_in_leaf: [50, 200]     # 更大的叶子最小样本
      lambda_l1: [0.0, 5.0]           # 更强的L1正则化
      lambda_l2: [0.0, 5.0]           # 更强的L2正则化
      max_depth: [6, 12]              # 控制树深度
      min_gain_to_split: [0.0, 0.3]   # 分裂增益控制

# ===========================================
# 输出配置
# ===========================================
output:
  file_naming:
    identifier_type: "unique_id"
    unique_id_digits: 3
    folder_name_prefix: "training_optimized"  # 区分优化版本
    show_id_in_log: true
  
  model_save:
    save_dir: "./models/lightgbm_optimized"
    model_name: "lightgbm_stock_model_optimized"
    save_format: ["pkl", "txt"]
    
  results_save:
    save_dir: "./results/lightgbm_optimized"
    save_predictions: true
    save_feature_importance: true
    save_metrics: true
    save_plots: true
    # 新增保存选项
    save_cv_results: true      # 保存交叉验证结果
    save_optimization_history: true  # 保存优化历史
    
  logging:
    log_level: "INFO"
    log_file: "./logs/lightgbm_training_optimized.log"
    console_output: true

# ===========================================
# 评估配置 - 增强版
# ===========================================
evaluation:
  # 更全面的评估指标
  metrics:
    - "rmse"
    - "mae"
    - "mape"
    - "r2_score"
    - "explained_variance"
    - "median_absolute_error"
    - "max_error"
    
  # 分层评估
  stratified_evaluation:
    enabled: true
    # 按目标值范围分层评估
    strata:
      - name: "small_changes"
        range: [-2, 2]
      - name: "medium_changes"
        range: [-5, 5]
      - name: "large_changes"
        range: [-10, 10]
    
  visualization:
    enabled: true
    plots:
      - "feature_importance"
      - "prediction_vs_actual"
      - "residuals"
      - "learning_curve"
      - "validation_curve"
      - "shap_summary"        # SHAP值分析
      - "prediction_intervals" # 预测区间

# ===========================================
# 其他配置 - 性能优化
# ===========================================
misc:
  # 并行计算
  n_jobs: -1
  
  # 内存优化 - 针对大数据集
  memory_optimization:
    enabled: true
    chunk_size: 50000      # 增加块大小
    use_float32: true      # 使用float32减少内存占用
    
  # 随机种子
  random_seed: 42
  
  # GPU 支持
  gpu_config:
    enabled: false
    device_type: "cuda"

# ===========================================
# 新增：数据质量控制
# ===========================================
data_quality:
  # 样本质量过滤
  sample_filtering:
    enabled: true
    # 移除目标值异常的样本
    target_outlier_threshold: 3.0  # 标准差倍数
    # 移除特征缺失过多的样本
    max_missing_features_ratio: 0.1
    
  # 特征质量控制
  feature_quality:
    enabled: true
    # 移除方差过小的特征
    min_variance_threshold: 0.01
    # 移除缺失值过多的特征
    max_missing_ratio: 0.05
    
  # 数据平衡处理
  data_balancing:
    enabled: true
    # 对极端值进行重采样
    method: "stratified"  # "undersampling", "oversampling", "stratified"
    target_bins: 10       # 将目标值分为10个区间进行平衡

# ===========================================
# 新增：模型集成
# ===========================================
ensemble:
  enabled: false  # 暂时禁用，可后续启用
  methods:
    - "bagging"
    - "boosting"
    - "stacking"
  base_models: 3
  
# ===========================================
# 新增：在线学习支持
# ===========================================
online_learning:
  enabled: false
  update_frequency: "daily"
  incremental_training: true
  model_drift_detection: true