# LightGBM 涨跌方向预测配置文件 - 超级防过拟合版本
# 针对严重过拟合问题的激进优化配置
# 目标：AUC从0.481提升到>0.55，缩小训练-测试差距

# ===========================================
# 数据配置
# ===========================================
data:
  data_dir: "./data/professional_parquet"
  
  direct_training:
    enabled: true
    data_format: "parquet"
    stock_name_column: "name"
    target_column: "涨跌幅"
    prediction_mode: "direction"
    exclude_columns:
      - "name"
      - "symbol"
    
  loading_options:
    encoding: "utf-8"
    validate_data: true
    
  # 🔧 更严格的数据预处理
  preprocessing:
    normalization:
      method: "robust"
      
    outlier_handling:
      enabled: true
      method: "winsorize"
      winsorize_limits: [0.05, 0.05]  # 🔧 更严格：5%和95%分位数截断

# ===========================================
# 训练配置（超级防过拟合）
# ===========================================
training:
  data_split:
    test_size: 0.2
    validation_size: 0.2            # 🔧 增加验证集到20%
    random_state: 42
    stratify: true
    time_series_split: true
    
  training_params:
    early_stopping_rounds: 30       # 🔧 更早停止（50→30）
    verbose: 25
    eval_metric: ["auc", "binary_logloss"]

# ===========================================
# LightGBM 模型参数（激进防过拟合）
# ===========================================
lightgbm:
  basic_params:
    objective: "binary"
    metric: "auc"
    boosting_type: "gbdt"
    num_leaves: 15                  # 🔧 大幅减少（31→15）
    learning_rate: 0.01             # 🔧 大幅降低（0.03→0.01）
    feature_fraction: 0.5           # 🔧 大幅降低（0.7→0.5）
    bagging_fraction: 0.5           # 🔧 大幅降低（0.7→0.5）
    bagging_freq: 1                 # 🔧 每轮都采样
    verbose: -1
    random_state: 42
    
  advanced_params:
    max_depth: 3                    # 🔧 大幅限制（5→3）
    min_data_in_leaf: 200           # 🔧 大幅增加（100→200）
    min_gain_to_split: 0.5          # 🔧 大幅提高（0.2→0.5）
    lambda_l1: 1.0                  # 🔧 大幅增加（0.2→1.0）
    lambda_l2: 1.0                  # 🔧 大幅增加（0.2→1.0）
    min_data_in_bin: 10             # 🔧 增加最小分箱样本
    max_bin: 128                    # 🔧 减少分箱数量（255→128）
    
  fit_params:
    num_boost_round: 200            # 🔧 大幅减少（500→200）

# ===========================================
# 特征选择（更严格）
# ===========================================
feature_selection:
  enabled: true
  methods:
    importance_based:
      enabled: true
      threshold: 0.005              # 🔧 提高重要性阈值
      
    correlation_based:
      enabled: true
      threshold: 0.85               # 🔧 更严格的相关性阈值

# ===========================================
# 输出配置
# ===========================================
output:
  file_naming:
    identifier_type: "unique_id"
    unique_id_digits: 3
    folder_name_prefix: "direction_ultra_robust"
    show_id_in_log: true
  
  model_save:
    save_dir: "./models/lightgbm_direction_ultra_robust"
    model_name: "lightgbm_direction_ultra_robust_model"
    save_format: ["pkl"]
    
  results_save:
    save_dir: "./results/lightgbm_direction_ultra_robust"
    save_predictions: true
    save_feature_importance: true
    save_metrics: true
    
  logging:
    log_level: "INFO"
    log_file: "./logs/lightgbm_direction_ultra_robust_training.log"
    console_output: true

# ===========================================
# 评估配置
# ===========================================
evaluation:
  metrics:
    - "auc"
    - "accuracy"
    - "precision"
    - "recall"
    - "f1_score"
    - "log_loss"

# ===========================================
# 其他配置
# ===========================================
misc:
  n_jobs: -1
  memory_optimization:
    enabled: true
    chunk_size: 5000                # 🔧 进一步减少chunk大小
  random_seed: 42

# ===========================================
# 🚨 激进防过拟合策略说明
# ===========================================
# 
# 问题诊断：
# - 训练集AUC: 0.759（过高）
# - 测试集AUC: 0.481（低于随机）
# - 差距: 0.278（严重过拟合）
#
# 激进优化策略：
#
# 1. 🎯 大幅降低模型复杂度
#    num_leaves: 63→31→15        # 复杂度降低75%
#    max_depth: 6→5→3           # 树深度大幅限制
#    min_data_in_leaf: 50→100→200 # 叶子节点样本数增加4倍
#
# 2. 🔒 激进正则化
#    lambda_l1: 0.1→0.2→1.0     # L1正则化增加10倍
#    lambda_l2: 0.1→0.2→1.0     # L2正则化增加10倍
#    min_gain_to_split: 0.1→0.2→0.5 # 分裂阈值增加5倍
#
# 3. 🎲 极大随机性
#    feature_fraction: 0.8→0.7→0.5  # 只用50%特征
#    bagging_fraction: 0.8→0.7→0.5  # 只用50%样本
#    bagging_freq: 5→3→1           # 每轮都随机采样
#
# 4. 🐌 超慢学习
#    learning_rate: 0.05→0.03→0.01  # 学习率降低5倍
#    early_stopping: 100→50→30      # 更早停止
#    num_boost_round: 1000→500→200  # 迭代数减少80%
#
# 5. 📊 数据质量提升
#    validation_size: 0.1→0.15→0.2  # 验证集增加到20%
#    winsorize_limits: [0.01,0.01]→[0.02,0.02]→[0.05,0.05] # 更严格异常值处理
#
# 期望改进目标：
# - 测试集AUC: 0.481 → >0.55
# - 训练-测试差距: 0.278 → <0.1
# - 整体泛化能力显著提升